#$Id: vis.mac 57 2012-09-09 22:37:49Z ripiccini $
#$Rev: 57 $
#
# Macro file for the initialization phase of "ATSA.cc"
# when running in interactive mode
#
# Sets some default verbose
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
#
# Use this open statement to create an OpenGL view:
#/vis/open OGL 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
#/vis/viewer/set/autoRefresh false
#/vis/verbose errors
#
# Draw geometry:
#/vis/drawVolume
#Defining the style of visualization
#/vis/viewer/set/style surface
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90. 90.
#/vis/viewer/panTo 4.5 0 cm
#/vis/viewer/set/viewpointVector -1 0 1
#
# Specify zoom value:
#/vis/viewer/zoom 5
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 300 cm
#
#Draw smooth trajectories at end of event, showing trajectory points
#as markers 2 pixels wide:
/vis/scene/add/trajectories smooth/
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
#/tracking/storeTrajectory 0
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only electrons:
#
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add e-
#/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set mu+ red
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
#/vis/viewer/set/autoRefresh true
#/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#

#/gps/particle ion
/gps/particle mu+
/tracking/verbose 0
/gps/source/multiplevertex true
/gps/pos/type Beam
/gps/pos/shape Ellipse
/gps/pos/centre 0. 0. 170. mm
/gps/pos/sigma_x 8. mm
/gps/pos/sigma_y 8. mm
#/gps/ang/type beam2d
/gps/ang/type user
/gps/hist/type theta


/gps/hist/point 0.000428571 2183
/gps/hist/point 0.00128571 2288
/gps/hist/point 0.00214286 2211
/gps/hist/point 0.003 2034
/gps/hist/point 0.00385714 1980
/gps/hist/point 0.00471429 1856
/gps/hist/point 0.00557143 1724
/gps/hist/point 0.00642857 1567
/gps/hist/point 0.00728571 1450
/gps/hist/point 0.00814286 1240
/gps/hist/point 0.009 1135
/gps/hist/point 0.00985714 938
/gps/hist/point 0.0107143 802
/gps/hist/point 0.0115714 728
/gps/hist/point 0.0124286 559
/gps/hist/point 0.0132857 485
/gps/hist/point 0.0141429 426
/gps/hist/point 0.015 337
/gps/hist/point 0.0158571 246
/gps/hist/point 0.0167143 212
/gps/hist/point 0.0175714 152
/gps/hist/point 0.0184286 105
/gps/hist/point 0.0192857 74
/gps/hist/point 0.0201429 61
/gps/hist/point 0.021 32
/gps/hist/point 0.0218571 23
/gps/hist/point 0.0227143 24
/gps/hist/point 0.0235714 16
/gps/hist/point 0.0244286 9
/gps/hist/point 0.0252857 7
/gps/hist/point 0.0261429 5
/gps/hist/point 0.027 2
/gps/hist/point 0.0278571 0
/gps/hist/point 0.0287143 0
/gps/hist/point 0.0295714 2
/gps/hist/point 5.97043 2
/gps/hist/point 5.97129 1
/gps/hist/point 5.97214 1
/gps/hist/point 5.973 4
/gps/hist/point 5.97386 3
/gps/hist/point 5.97471 9
/gps/hist/point 5.97557 11
/gps/hist/point 5.97643 15
/gps/hist/point 5.97729 28
/gps/hist/point 5.97814 26
/gps/hist/point 5.979 51
/gps/hist/point 5.97986 76
/gps/hist/point 5.98071 80
/gps/hist/point 5.98157 110
/gps/hist/point 5.98243 148
/gps/hist/point 5.98329 173
/gps/hist/point 5.98414 285
/gps/hist/point 5.985 308
/gps/hist/point 5.98586 378
/gps/hist/point 5.98671 495
/gps/hist/point 5.98757 597
/gps/hist/point 5.98843 718
/gps/hist/point 5.98929 854
/gps/hist/point 5.99014 963
/gps/hist/point 5.991 1197
/gps/hist/point 5.99186 1320
/gps/hist/point 5.99271 1399
/gps/hist/point 5.99357 1553
/gps/hist/point 5.99443 1682
/gps/hist/point 5.99529 1853
/gps/hist/point 5.99614 1962
/gps/hist/point 5.997 2124
/gps/hist/point 5.99786 2204
/gps/hist/point 5.99871 2181
/gps/hist/point 5.99957 2274

#/gps/direction 0 0 1
/gps/ene/type Gauss 
/gps/ene/mono 3.622 MeV 
/gps/ene/sigma 0.230 MeV



/run/beamOn 10000
